rootProject.name = "OTTCLONES"

// netclone is manually managed (patched binary on builds branch)
// include("netclone")
include("animepaheclone")
include("animesaltclone")
include("animedekhoclone")
include("movieboxinclone")
include("anizoneclone")
include("multimoviesclone")
// netmirrorclone removed (conflicts with RVE/netclone same package)
// include("netmirrorclone")
include("anikotoclone")
include("anidbclone")
include("aninekoClone")
include("castletvclone")
include("anikageclone")
include("hdhub4uclone")
include("animesugeclone")
