rootProject.name = "OTTCLONES"

include("netclone")
include("animepaheclone")
include("animesaltclone")
include("animedekhoclone")
include("movieboxinclone")
include("anizoneclone")
include("multimoviesclone")
include("netmirrorclone")
include("anikotoclone")
include("anidbclone")
include("aninekoClone")
include("castletvclone")
include("anikageclone")
